### PR TITLE
Task #3553 2 the page "blinks" when transitioning from one navbar menu to another. 

### PR DESCRIPTION
**Pull request by macs03**
second part of bug #3553 the page "blinks" when transitioning from one navbar menu to another. ex) when I click "reliable and light" menu in navbar, the page "blinks" and then goes to the right section. This blinking should be removed.

### CODE REVIEW

**Comment by verysanghee** [comment]
does the job partly.

**Comment by verysanghee** [comment]
@tiwariav can you review this PR and if possible improve it?

**Comment by tiwariav** [comment]
@verysanghee sure. I'll review it once and update if anything can be done.

**Comment by tiwariav** [comment]
The page blinked because in the click event handler function, "event.preventDefault()" was not present, hence the default behavior of <a> tag caused the blinking issue.
Removing 'href' is one solution, but not recommended, 
- as the behavior is not consistent across browsers for <a> tags without 'href'.
- and you loose the capability to link parts of the page as /url/of/some-page#some-part

**Comment by tiwariav** [comment]
@verysanghee fixed the issue and made a new PR. Check and let me know.

**Comment by verysanghee** [comment]
fixed in PR #415 by @tiwariav thus closing this PR.

**Pull request closed without merging**
