### PR TITLE
Set debug false

### PR DESCRIPTION
**Pull request by pcoder**
Hi @all, I proposed this PR to resolve the issue #3538 wherein we have/had `DEBUG=True` set in settings/base.py in production. And due to this, we were/are always loading the settings defined in local.py rather than prod.py. This PR also introduces the use of memcached cache for production and LocMemcache for development (It was always using/It still uses LocMemcache in production). In order to test this PR, you may need to set `DEBUG=True` in your .env file.

### CODE REVIEW

**Comment by amarynets** [comment]
@m-ravi why did you use .env file for getting DEBUG flag?

**Comment by pcoder** [comment]
Thats to allow users to set DEBUG flag, independent of the code @amarynets

**Comment by amarynets** [comment]
@pcoder Is it better than using local and prod file for it?

**Comment by pcoder** [comment]
We choose local or prod based on the value we set to DEBUG @amarynets Please refer to the code.

**Pull request merged**
