### PR TITLE
#3588 navbar language options

### PR DESCRIPTION
**Pull request by tiwariav**

### CODE REVIEW

**Comment by verysanghee** [comment]
This task received a feedback and we want to change the lang option as following. https://redmine.ungleich.ch/issues/3603

**Comment by tiwariav** [comment]
@verysanghee required changes done.

**Comment by verysanghee** [comment]
tested and nicely done.

**Comment by verysanghee** [comment]
@tiwariav can you resolve merge conflict please? FYI, we always deploy on Thursday night, it'll be great if you can resolve conflicts from your PRs beforehand. :)

**Comment by tiwariav** [comment]
@verysanghee conflicts resolved

**Comment by verysanghee** [comment]
@tiwariav tested, and this PR has problem: When I'm already in Deutsch page menu (ex: Warum Data Center Light?) and click the navbar menu such as "Skalierung" , the page shows "Scaling" which is EN page. The language option does not stay consistent during navbar menu click. This cross-language bug needs to be fixed.

**Comment by tiwariav** [comment]
merged and continued in PR #424

**Pull request closed without merging**
