### PR TITLE
Staging fix text in highlights, added Font 'Lato', and outline none i…

### PR DESCRIPTION
**Pull request by HenryGBC**
Staging fix text in highlights, added Font 'Lato', and outline none in all buttons

### CODE REVIEW

**Comment by levivm** [comment]
Looks good.

**Comment by verysanghee** [comment]
the btn outline is still there when we tested on dev 
screen shot 2017-06-23 at 00 48 04

**Comment by verysanghee** [comment]
And "Our data center..." line needs to be right-aligned, in this PR left-alignment does not look great.

**Comment by verysanghee** [comment]
This PR is too behind from current master and missed time for updating. Thus closing it.

**Pull request closed without merging**
