### PR TITLE
Fixed a responsive issue in signup/email confirmation

### PR DESCRIPTION
**Pull request by pcoder**
After we sign up, we get a message saying "Thank you for signing up. We have sent an email to you. Please follow the instructions in it to activate your account. Once activated, you can login using login"

And after we confirm the email, by following the link we get to a page that says "Your account has been activated. You can now login"

Both these pages have a wrong style causing responsive issue. I fix this in this PR.

### CODE REVIEW

**Comment by verysanghee** [comment]
@pcoder redmine #3440 #3439, isn't it? I assigned it to Henry but looks like you took care of it, I'll reassign it to you. :)

**Comment by verysanghee** [comment]
screen shot 2017-06-18 at 16 36 39

**Comment by verysanghee** [comment]
@pcoder For improvement the btn needs center-align and color like the rest of btn styles, and the msg needs line change. But this PR is definitely an improvement from previous state.

**Comment by pcoder** [comment]
The issue that @verysanghee mentioned above is not at all covered in this PR. That is to be be fixed separately.

**Pull request merged**
