### PR TITLE
Task/3718 downtime page

### PR DESCRIPTION
**Pull request by tiwariav**

### CODE REVIEW

**Comment by tiwariav** [comment]
@verysanghee should we close this PR?

**Comment by tiwariav** [comment]
I suggest that we keep the html page from this PR for any possible future use, and merge this PR too?
@verysanghee @pcoder

**Comment by verysanghee** [comment]
yep let's merge it then

**Comment by pcoder** [comment]
I think the static html is good and probably its best to handle this at the reverse proxy than in Django. So, I am against changes in urls.py for this :)

**Comment by tiwariav** [comment]
reverted the changes to `urls.py`.

**Pull request merged**
