### PR TITLE
Bugfix/3634 navbar options added on payments, order-success, order-confirmation

### PR DESCRIPTION
**Pull request by tiwariav**

### CODE REVIEW

**Comment by pcoder** [comment]
Could you please resolve the conflicts?

**Comment by tiwariav** [comment]
@pcoder conflicts resolved

**Comment by tiwariav** [comment]
@pcoder apart from the indentation, was there anything else to reformat?

**Comment by verysanghee** [comment]
payment navbar style is not consistent with the rest of the landing. 
screen shot 2017-08-19 at 21 28 54

**Comment by verysanghee** [comment]
when clicking navbar on landing I'm often redirected to 404 error to https://dynamicweb-development.ungleich.ch/de/datacenterlightundefined/

**Pull request merged**
