### PR TITLE
task #3604 footer links

### PR DESCRIPTION
**Pull request by tiwariav**
:hover :focus :active color changed to #ddd

### CODE REVIEW

**Comment by verysanghee** [comment]
tested and looks good.

**Comment by verysanghee** [comment]
@tiwariav can you resolve the conflicts?

**Comment by tiwariav** [comment]
@verysanghee conflicts resolved

**Comment by verysanghee** [comment]
on mobile, the footer color does not change on touch. I think it should @tiwariav

**Pull request merged**
