### PR TITLE
Task/3842 de number formatting

### PR DESCRIPTION
**Pull request by tiwariav**

### CODE REVIEW

**Comment by tiwariav** [comment]
Need clarification on whether we are following this guideline or not:

`The Swiss number formatting depends on the type of number that is being formatted. For monetary values, a comma is used as the thousand separator and a decimal point for the decimal separator. For all other numbers, a comma is used as decimal separator and a space as thousand separator.`

**Comment by verysanghee** [comment]
I think above guideline is correct.

**Comment by verysanghee** [comment]
for monetary values a "high-coma" is used.
E.g. 10'000 CHF

**Comment by tiwariav** [comment]
closing this as it is redone in a simpler way in #580

**Pull request closed without merging**
