### PR TITLE
Bugfix/3645 navbar movement on modal show/hide

### PR DESCRIPTION
**Pull request by tiwariav**

### CODE REVIEW

**Comment by verysanghee** [comment]
I can't reproduce this bug on mac so far, will have to leave it to @pcoder for testing/reviewing

**Comment by pcoder** [comment]
The code looks good to me. 
I tested for the navbar movement on both firefox and chrome and found that the PR does what its meant to do.

**Comment by pcoder** [comment]
Just a remark, perhaps not related to the PR.

On my chrome `Version 54.0.2840.90 Fedora Project (64-bit)`, in the my orders page, when I click on the "Cancel Order", I observed the following two strange behaviors.
1. When I click the "Cancel Order" button, the browser sends a request to the server as it opens the modal. I think we don't want this and this does not happen on Firefox.
2. On smaller screens, if I am at the bottom of the list of orders, and then if I click the "Cancel Order" button, the page (in the background) slides to the top. I guess, the first point may be the cause of this.

**Comment by verysanghee** [comment]
@pcoder The "Cancel Order" btn does not really have a sensible function (it just deletes one item from the order list) so in the future we probably want to get rid of it. For really deleting/terminating the order we have "terminating order" in VM dashboard.

**Comment by pcoder** [comment]
@verysanghee Makes sense in that case.

**Pull request merged**
