### PR TITLE
fixed credit card input issue

### PR DESCRIPTION
**Pull request by levivm**
Credit card input disappeared in 1.0.15 and this is the bugfix for that

### CODE REVIEW

**Comment by verysanghee** [comment]
In dynamicweb-develop, the credit card input field is back but Henry's latest VM page is reverted.

**Comment by pcoder** [comment]
I wonder how this PR is going to solve any issue. All we seem to be doing in the PR is cleaning up unwanted code.

**Comment by levivm** [comment]
@pcoder yep, It will fix that issue, I already test it. 

@verysanghee let me check it out.

**Comment by levivm** [comment]
@verysanghee what exactly about `Henry's latest VM page`.

**Comment by verysanghee** [comment]
What info do I need to give you Levi?

**Pull request merged**
